### ISSUE TITLE
LDAP users are not removed from dropdown when they are already members of the custom group.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/customgroups#90]
### Steps to reproduce

0. Set up a ldap server.
1. Create a custom group 'ldap_group' using a user from the ldap server.
2. Add ldap users to the custom group 'ldap_group'.
3. Try to add an already added ldap user to the custom group 'ldap_group'.

### Expected behaviour
Users which are already members of the customgroup doesn't appear in the dropdown.

### Actual behaviour
Ldap users which are already members of the customgroup still appear in the dropdown.
When choosing them, they cannot be added though, which is correct.

![screen shot 2017-08-22 at 16 49 54](https://user-images.githubusercontent.com/9048796/29571835-9bcd0cce-875a-11e7-8241-d312ca9bd0f8.png)

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
10.0.3beta1
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.3.0","versionstring":"10.0.3 beta","edition":"Community","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No.

**Logs**
```
```

### Client configuration

**Browser**
Chrome

cc @PVince81

**Comment by PVince81** [comment]
There is some custom code to exclude already existing users from the result list. Maybe there is a user id format mismatch there.

**Comment by PVince81** [comment]
Only happen in customgroups autocomplete, not in the sharing one.

**Comment by PVince81** [comment]
Argh, now I see that the code is completely wrong.

The search for existing members is only checking if there is a user_id that matches the pattern and is already a member of the custom group. This means it only ever works with user ids, which in LDAP are usually those unreadable UUIDs.

Steps to reproduce without LDAP:

1. Create a user "user1" with display name "One"
1. Create a custom group "customgroup1"
1. Add "One" to "customgroup1"
1. Try adding "One" again

Since "One" does not match the user_id "user1", the code does return that user as available choice.

There are two possible fixes:
1) Fix the backend to also join on the user account table to be able to resolve the display name
or
2) Fix the frontend to exclude known members from the received list. (this one would break if we ever introduce pagination as not all known members would be available)

**Comment by PVince81** [comment]
and if we say we don't allow apps to join with the oc_accounts table, then it gets trickier:

3) Need to first get all users that match the given pattern from the oc_accounts table using IUserManager->search(). Then get all members from the group. And then intersect on user_id.

I think there is likely no other way than 3) because for LDAP we want the "search terms" logic that uses the extra fields to be used.

**Comment by PVince81** [comment]
From what I see it seems we already went for solution 3) before, but weren't using the correct methods.

Since 10.0.1 there is a method `IUserManager::find()` to search all fields. That method is also used by the sharees autocomplete code.

This PR makes it use a similar approach: https://github.com/owncloud/customgroups/pull/106
